---
title: "CV"
description: |
output:
  distill::distill_article:
    self_contained: false
    toc: true
    css: theme.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Education

### Degrees

**University of California Irvine**  [2019 - 2025 (expected)]{.date} \
Doctor of Philosophy - Statistics (GPA: 3.9)\
Dissertation: Advances in Bayesian Nonparametric models for clustering \
Advisors: [Erik Sudderth](https://ics.uci.edu/~sudderth/) and [Michele Guindani](https://www.micheleguindani.info/)

**Bocconi University** \
Master of Science - Economic and Social Sciences (GPA: 4.0) [2016 - 2019]{.date} \
Research Thesis: A Sticky Hierarchical Pitman-Yor Process as a Prior for Hidden Markov Models \
Advisor: [Antonio Lijoi](https://mypage.unibocconi.eu/antoniolijoi/) \
Bachelor of Science - Economics and Management for Arts  (GPA: 4.0) [2012 - 2015]{.date} \

### Training programs

**University of California Irvine** \
Mentoring Excellence Program [2023]{.date} \
CITI Basic HRP Course for Social and Behavioral Investigators [2023]{.date} \
Division of Teaching Excellence and Innovation pedagogical training [2020]{.date}

**Bocconi University** \
Visiting Student at the IGIER-BIDSA Research Center [2017-2018]{.date} \

## Publications

### Statistical methodology

- **Ricci, F. Z.**, Sudderth, E., Lee, J., Peters, M., Vannucci, M. & Guindani, M.,  (2024, submitted) _Bayesian temporal biclustering with applications to multi-subject neuroscience studies._ 
arXiv preprint arXiv:2406.17131. 
<a href="https://arxiv.org/abs/2406.17131" target="_blank" title="Paper"> (link) </a>

- **Ricci, F. Z.**, Guindani, M., & Sudderth, E. (2022). _Thinned random measures for sparse graphs with overlapping communities._ Advances in Neural Information Processing Systems, 35, 38162-38175.
<a href="https://proceedings.neurips.cc/paper_files/paper/2022/file/f9668d223e713943634dce9c66e8f2c1-Paper-Conference.pdf" target="_blank" title="Paper"> (link) </a> &nbsp; 

### Statistics education

- Dogucu, M., Demirci, S., Bendekgey, H., **Ricci, F. Z.**, & Medina, C. M. (2024, submitted). _Undergraduate data science education: Who has the microphone and what are they saying?._ arXiv preprint arXiv:2403.03387. 
<a href="https://arxiv.org/abs/2403.03387" target="_blank" title="Paper"> (link) </a>

- **Ricci, F. Z.**, Medina, C. M., & Dogucu, M. (2024, under revision). _Automated grading workflows for providing personalized feedback to open-ended data science assignments._ arXiv preprint arXiv:2309.12924. 
<a href="https://arxiv.org/abs/2309.12924" target="_blank" title="Paper"> (link) </a>

- Rummerfield, W., **Ricci, F. Z.**, & Dogucu, M. (2021). _Training graduate students to teach statistics and data science from a distance._ In Proceedings of the IASE 2021 Satellite Conference. International Association for Statistical Education.
<a href="https://iase-web.org/documents/papers/sat2021/IASE2021%20Satellite%20116_RUMMERFIELD.pdf?1649974209" target="_blank" title="Paper"> (link) </a>

### Applied Statistics

- Migliavada, R., Ricci, M., **Ricci, F. Z.**, G. Garavelli, L. Torri (2024, in preparation). _Calories on restaurant menus are ineffective in combating obesity, regardless of how they are presented._

- Migliavada, R., **Ricci, F. Z.**, Denti, F., Haghverdian, D., & Torri, L. (2022). _Is purchasing of vegetable dishes affected by organic or local labels? Empirical evidence from a university canteen._ Appetite, 173, 105995. 
<a href="https://www.sciencedirect.com/science/article/abs/pii/S0195666322000861" target="_blank" title="Paper"> (link) </a>  &nbsp; 

- Migliavada, R., **Ricci, F. Z.**, & Torri, L. (2021). _A three-year longitudinal study on the use of pre-ordering in a university canteen._ Appetite, 163, 105203.
<a href="https://www.sciencedirect.com/science/article/pii/S0195666321001100?casa_token=iul1lGSFkBkAAAAA:Pq3OHZh5qvbIAjUzCKffo4jUq1G6TVwwWovyr8I8EX4qi22Zo4-bIoOaKACHWgF5feuLRZXX" target="_blank" title="Paper"> (link) </a>  &nbsp; 

### Software

- **Ricci, F. Z.** R package tggp4networks: _Modeling of network data with Thinned Generalized Gamma Process._ GitHub, March 2023.
<a href="https://github.com/federicazoe/tggp4networks" target="_blank" title="GitHub Repo"> (link) </i> </a> &nbsp;

- **Ricci, F. Z.**, Medina, C. & Dogucu, M. _R package gradetools: Tools to Assist with Providing Grades and Personalized Feedback to Students._ GitHub, March 2022.
<a href="https://federicazoe.github.io/gradetools/" target="_blank" title="Vignette"> (link) </i> </a> &nbsp;

## Presentations

### Talks

- _BayesBATS: a program for advancing Bayesian thinking in STEM education_ \
  Joint Statistical Meetings, Portland (OR), Aug 2024 (forthcoming)

- _Bayesian temporal biclustering with applications to multi-subject neuroscience studies_  \ 
  Meeting of the International Society for Bayesian Analysis, Venice (Italy), Jul 2024 (forthcoming)
  
- _Building Data Science Education Research Plan for Teacher-Scholars_ \ 
  Electronic Conference on Teaching Statistics, online, June 2024  <a href="https://www.causeweb.org/cause/ecots/ecots24/program/breakout/building-data-science-education-research-plan-for-teacher-scholars" target="_blank" title="Abstract"> (link) </i> </a>
  
-  _A Bayesian model for clustering subjects and measurements with application to brain imaging studies_ \
  Graduate student showcase of ASA section on Statistics in Imaging, online, Apr 2024 
  
- _A Bayesian model for clustering subjects and measurements in multivariate time-series_  \
   Colloquium of the Dept. of Mathematics and Statistics, University of West Florida, Mar 2024.
   
- _Thinned random measures for sparse networks with overlapping communities_ \
  International Day of Women in Statistics and Data Science, online, 2022.
  <a href="https://drive.google.com/file/d/1AYpYQldhowA2ufsABTdaqjxY2NAOEysp/view?usp=sharing" target="_blank" title="Slides">  (link) </a> &nbsp;
  
### Workshops

- **Ricci, F.Z.**, Medina, C. _Automate your grading workflow with gradetools: a grading assistant in RStudio_ \
 US Conference on Teaching Statistics (USCOTS), State College (PA), May 2023 ([link](https://github.com/federicazoe/gradetools-uscots2023))
  
- **Ricci, F.Z.**, Medina, C. & Dogucu, M. _gradetools: a grading assistant in RStudio_ \
  Researchers of Statistics Education (RoSE) conference, online, 2023 ([link](https://federicazoe.github.io/gradetools-RoSE/#1))
  
### Posters

- _See you at the posterior line: learning Bayesian modeling with an online racing game_ \
 Bayesian Young Statisticians Meeting, Venice (Italy), Jun 2024 (forthcoming) <a href="https://drive.google.com/file/d/1m4dp983WWe4YplFMqhFIi7P2CVZBl5hI/view" target="_blank" title="Poster">  (link) </a> &nbsp;

- _See you at the Posterior line: an online racing game to teach Bayesian data analysis_ \
  Electronic Conference On Teaching Statistics, online, Jun 2024 (forthcoming) <a href="https://federicazoe.github.io/bayes-games/" target="_blank" title="Webpage">  (link) </a> &nbsp; 
  
- _Dynamic biclustering for multi-subject neuroscience studies_ \
  Biomedical Data Science Workshop, UC Irvine, 2024 (Awarded best poster) <a href="https://drive.google.com/file/d/1_j9uXeucFznl74tM8qRPCnEOcVt0Qz4I/view" target="_blank" title="Poster">  (link) </a> &nbsp;
  
- _Modeling sparse graphs with overlapping communities via thinned random measures_  \
  Objective Bayes Conference, UC Santa Cruz, 2022 \
  Meeting of the International Society for Bayesian Analysis, Montreal (Canada), 2022 (Awarded among best posters in Bayesian Nonparametric category)  \
  <a href="https://drive.google.com/file/d/1qxl88y9D5Zi0tq3gkmXfHz44VnHaSWct/view?usp=sharing" target="_blank" title="Poster">  (link) </a> &nbsp;
 
  
  
### Blog posts

- **Ricci, F.Z.** & Dogucu, M. _Assisted grading with Gradescope_ \
  Published on Data Pedagogy in 2021 ([link](https://www.datapedagogy.com/posts/2021-08-12-assisted-grading-with-gradescope/))
  
- **Ricci, F.Z.**, Rummerfield, W. & Dogucu, M. _Tips and Tools for Asynchronous Class Videos_ \
  Published on Data Pedagogy in 2021 ([link](https://www.datapedagogy.com/posts/2021-01-08-video-production-tips/))
  
- Rummerfield, W., **Ricci, F.Z.** & Dogucu, M. _Engaging Students in Remote Classes_
  Published on Data Pedagogy in 2020 ([link](https://www.datapedagogy.com/posts/2020-09-10-student-engagement-remote/))

## Teaching

### Teaching Assistant

**University of California Irvine** [2020 - 2021]{.date} \
[Evaluations]{.date} \
Stats 7 (Basics Statistics) [<a href='evaluations/2020_spring_stats_7_C1_C2.pdf' class="icon"> <i class='fa fa-clipboard'></i> </a>]{.date}\
Stats 8 (Introduction to Biostatistics) [<a href='evaluations/2021_fall_stats_8_dis1_dis2.pdf' class="icon"> <i class='fa fa-clipboard'></i> </a>]{.date}\
Stats 67 (Introduction to Probability and Statistics for Computer Science) [<a href='evaluations/2021_winter_stats_67_A1_A2.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> <a href='evaluations/2020_fall_stats_67_B1_B2.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> <a href='evaluations/2020_summer_stats_67.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> <a href='evaluations/2020_winter_stats_67_B1_B2.pdf' class="icon"> <i class='fa fa-clipboard'></i></a>]{.date}\
Stats 68 (Statistical Computing and Exploratory Data Analysis) [<a href='evaluations/2021_spring_stats_68.pdf' class="icon"> <i class='fa fa-clipboard'></i> </a>]{.date}

### Guest Lectures

See you at the posterior line: a game-based activity for the Beta-Binomial model [2024]{.date}\
  Stats 115 (Introduction to Bayesian Data Analysis) at  UC Irvine
  

### Workshops

Writing your honors thesis [2024]{.date} \    
  Workshop for ICS honors-program undergraduates at UC Irvine  ([link](https://github.com/federicazoe/writing-ws-honors-sp24))\

Quarto for writing data analysis reports and academic articles [2023]{.date} \    
  Workshop for graduate students at UC Irvine  ([link](https://github.com/federicazoe/brownbag-quarto-doc/))\
  
Let's get ready for the data analysis qualifying exam [2023]{.date} \    
  Workshop for graduate students at UC Irvine  \
  
Writing a data analysis report [2023]{.date} \    
  Workshop for the ISI-BUDS undergraduate research program at UC Irvine ([link](https://github.com/isi-buds/program-2023/tree/main/writing-workshop))  \


## Service

### Service to profession 

- Mentor for Pacific Alliance for Low-income Inclusion in Statistics and Data Science 2024-2025
- Reviewer for Undergraduate Class Project Competition (USCLAP) 2024
- Reviewer for Computational Statistics and Data Analysis 
- Reviewer for Artificial Intelligence and Statistics 2024
- Assisted M. Hu and K. J. Ross at ASA traveling course on teaching Bayes 2023
- Assisted M. Dogucu, M. Hu and A. Harring at Bayes BATS program 2023 (Tier I and Tier II)

### Service to department

- Founder and organizer of BrownBag seminar series [2021 - present]{.date} \
  Seminars and workshops promoting graduate students' professional development in the Statistics department at UC Irvine

- UC Irvine Statistics First-Year Peer-Mentoring Program [2021 - present]{.date}

## Awards and Fellowships

- Recipient of Hasso-Plattner Institute for Machine Learning and Data Science Fellowship at UC Irvine (2022-2025)
<!--- Travel award, Meeting of the International Society for Bayesian Analysis, Montreal (2022)
- Travel award, Objective Bayes Conference, Santa Cruz (2022) -->
- Recipient of Division of Teaching Excellence and Innovation Summer Fellowship (2020)
- Newcomb Graduate Student Award for outstanding performance at qualifying exam (UC Irvine Statistics Department, 2020)
- Best TA of the Year, honorary mention (UC Irvine Statistics Department, 2019-20)


## Professional Memberships

- Institute of Mathematical Statistics (2024 - present)
- American Statistical Association (2024 - present)
- International Society for Bayesian Analysis (2022 - present)

