---
title: "Teaching"
description: |
  <q style="font-size:18px">  Preserving the spirit of childood for life means preserving the curiosity of learning, the pleasure to understand, the desire to communicate. </q> 
  <br> 
  <small style="font-size:12px;margin-bottom:0"> (translated from <a href='https://en.wikipedia.org/wiki/Bruno_Munari' style="color:black; text-decoration: none">B. Munari</a>) </small>
output:
  distill::distill_article:
    self_contained: false
    toc: true
    css: theme.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Courses

Below is a list of courses that I have been a TA for at UC Irvine.

<table>
  <!-- Header -->
  <tr>
    <th> Course </th>
    <th> Terms </th>
    <th> Evaluations </th>
  </tr>
  
  <!-- Stats 68 -->
  <tr>
    <td style="font-size: 11px"> <a href='https://stats68-sp21.netlify.app/' target="_blank">  Stats 68 - Statistical Computing and Exploratory Data Analysis </a>  </td>
    <td style="font-size: 11px"> Spring 2021 </td>
    <td style="font-size: 10px; text-align: center;">
         <a href='evaluations/2021_spring_stats_68.pdf' class="icon"> <i class='fa fa-clipboard'></i> </a>
    </td>
  </tr>
  
  <!-- Stats 67 -->
  <tr>
    <td style="font-size: 11px"> <a href='https://www.stats4cs.com/' target="_blank">  Stats 67 - Introduction to Probability and Statistics for Computer Science </a> </td>
    <td style="font-size: 11px">
      <p class="compact"> Winter 2021 </p>
      <p class="compact"> Fall 2020 </p>
      <p class="compact"> Summer 2020 </p>
      <p class="compact"> Winter 2020 </p>
    </td>
    <td style="font-size: 10px; text-align: center;">
       <p class="compact"> <a href='evaluations/2021_winter_stats_67_A1_A2.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> </p>
       <p class="compact"> <a href='evaluations/2020_fall_stats_67_B1_B2.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> </p>
       <p class="compact"> <a href='evaluations/2020_summer_stats_67.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> </p>
       <p class="compact"> <a href='evaluations/2020_winter_stats_67_A1_A2.pdf' class="icon"> <i class='fa fa-clipboard'></i></a> </p>       
    </td>
  </tr>
  
  <!-- Stats 8 -->
  <tr>
    <td style="font-size: 11px"> <a href='http://catalogue.uci.edu/allcourses/stats/' target="_blank">  Stats 8 - Introduction to Biostatistics </a>  </td>
    <td style="font-size: 11px"> Fall 2021 </td>
    <td style="font-size: 10px; text-align: center;">
         <a href='evaluations/2021_fall_stats_8_dis1_dis2.pdf' class="icon"> <i class='fa fa-clipboard'></i> </a>
    </td>
  </tr>
  
  <!-- Stats 7 -->
  <tr>
    <td style="font-size: 11px"> <a href='http://catalogue.uci.edu/allcourses/stats/' target="_blank">  Stats 7 - Basic Statistics </a>  </td>
    <td style="font-size: 11px"> Spring 2020 </td>
    <td style="font-size: 10px; text-align: center;">
         <a href='evaluations/2020_spring_stats_7_C1_C2.pdf' class="icon"> <i class='fa fa-clipboard'></i> </a>
    </td>
  </tr>

</table>

### Tasks

Examples of work I have done:

<ul class="compact">
 <li>  holding office hours and lab sessions </li>
 <li>  making educational videos </li>
 <li>  curating online discussion spaces </li>
 <li>  creating exams and quizzes </li> 
 <li>  assigning grades and personalized feedback </li>
</ul> 

### Tools

Some of the tools that I have worked with:

<ul class="compact">
 <li> Canvas </li>
 <li>  Gradescope </li>
 <li>  iMovie </li>
 <li>  Piazza </li>
 <li>  RStudio </li>
 <li>  YuJa </li>
 <li>  Zoom </li>
</ul>

### Awards 

<p class="compact"> I really enjoy teaching and learning how to improve at teaching. </p>

<p> As a result of my commitment to teaching: </p>

* At the end of my first year as a PhD student, I received an honorable mention as best TA of the year in the Department of Statistics at UCI.

* In summer 2020, I was selected for the [Division of Teaching Excellence and Innovation Summer Fellowship](https://dtei.uci.edu/call-for-dtei-graduate-fellows/). As a DTEI fellow, I worked with [Dr. Dogucu](https://mdogucu.ics.uci.edu//index.html) on topics relevant to remote-learning, such as [students' engagement](https://www.datapedagogy.com/posts/2020-09-10-student-engagement-remote/) in remote classes and [video editing](https://www.datapedagogy.com/posts/2021-01-08-video-production-tips/).
